"""empty message

Revision ID: fce197c104ae
Revises: 936eb9c1df15
Create Date: 2022-05-28 15:30:32.338089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce197c104ae'
down_revision = '936eb9c1df15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
