"""empty message

Revision ID: 3f06b7860799
Revises: 863c23c18e58
Create Date: 2022-05-08 15:01:43.258901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f06b7860799'
down_revision = '863c23c18e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
