"""empty message

Revision ID: 53a3fb476395
Revises: 3f06b7860799
Create Date: 2022-05-08 15:01:59.899040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a3fb476395'
down_revision = '3f06b7860799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
